# Generated by Django 3.2.25 on 2024-05-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата изменения'),
        ),
    ]
