# Generated by Django 3.2.25 on 2024-05-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Введите номер версии', verbose_name='Номер версии')),
                ('name', models.CharField(help_text='Введите название версии', max_length=150, verbose_name='Название версии')),
                ('is_active', models.BooleanField(default=False, help_text='Отметьте активность версии', verbose_name='Активная версия?')),
                ('product', models.ForeignKey(blank=True, help_text='Введите версию продукта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version', to='catalog.product', verbose_name='версия продукта')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
            },
        ),
    ]
